export interface Country {
  value: string;
  longName: string; // Official long name or empty
  flag: string; // 🇦🇫 style emoji
}

export const countriesData: Country[] = [
  {
    value: 'Afghanistan',
    longName: 'Islamic Republic of Afghanistan',
    flag: '🇦🇫',
  },
  { value: 'Albania', longName: '', flag: '🇦🇱' },
  { value: 'Algeria', longName: '', flag: '🇩🇿' },
  { value: 'Andorra', longName: '', flag: '🇦🇩' },
  { value: 'Angola', longName: '', flag: '🇦🇴' },
  { value: 'Antigua and Barbuda', longName: '', flag: '🇦🇬' },
  { value: 'Argentina', longName: '', flag: '🇦🇷' },
  { value: 'Armenia', longName: '', flag: '🇦🇲' },
  { value: 'Australia', longName: '', flag: '🇦🇺' },
  { value: 'Austria', longName: '', flag: '🇦🇹' },
  { value: 'Azerbaijan', longName: '', flag: '🇦🇿' },
  { value: 'Bahamas', longName: '', flag: '🇧🇸' },
  { value: 'Bahrain', longName: '', flag: '🇧🇭' },
  { value: 'Bangladesh', longName: '', flag: '🇧🇩' },
  { value: 'Barbados', longName: '', flag: '🇧🇧' },
  { value: 'Belarus', longName: '', flag: '🇧🇾' },
  { value: 'Belgium', longName: '', flag: '🇧🇪' },
  { value: 'Belize', longName: '', flag: '🇧🇿' },
  { value: 'Benin', longName: '', flag: '🇧🇯' },
  { value: 'Bhutan', longName: '', flag: '🇧🇹' },
  {
    value: 'Bolivia',
    longName: 'Plurinational State of Bolivia',
    flag: '🇧🇴',
  },
  { value: 'Bosnia and Herzegovina', longName: '', flag: '🇧🇦' },
  { value: 'Botswana', longName: '', flag: '🇧🇼' },
  { value: 'Brazil', longName: '', flag: '🇧🇷' },
  { value: 'Brunei', longName: 'Negara Brunei Darussalam', flag: '🇧🇳' },
  { value: 'Bulgaria', longName: '', flag: '🇧🇬' },
  { value: 'Burkina Faso', longName: '', flag: '🇧🇫' },
  { value: 'Burundi', longName: '', flag: '🇧🇮' },
  { value: 'Cabo Verde', longName: '', flag: '🇨🇻' },
  { value: 'Cambodia', longName: '', flag: '🇰🇭' },
  { value: 'Cameroon', longName: '', flag: '🇨🇲' },
  { value: 'Canada', longName: '', flag: '🇨🇦' },
  { value: 'Central African Republic', longName: '', flag: '🇨🇫' },
  { value: 'Chad', longName: '', flag: '🇹🇩' },
  { value: 'Chile', longName: '', flag: '🇨🇱' },
  { value: 'China', longName: 'People’s Republic of China', flag: '🇨🇳' },
  { value: 'Colombia', longName: '', flag: '🇨🇴' },
  { value: 'Comoros', longName: '', flag: '🇰🇲' },
  { value: 'Congo', longName: 'Congo‑Brazzaville', flag: '🇨🇬' },
  { value: 'Costa Rica', longName: '', flag: '🇨🇷' },
  { value: 'Croatia', longName: '', flag: '🇭🇷' },
  { value: 'Cuba', longName: '', flag: '🇨🇺' },
  { value: 'Cyprus', longName: '', flag: '🇨🇾' },
  { value: 'Czechia', longName: 'Czech Republic', flag: '🇨🇿' },
  { value: 'Democratic Republic of the Congo', longName: '', flag: '🇨🇩' },
  { value: 'Denmark', longName: '', flag: '🇩🇰' },
  { value: 'Djibouti', longName: '', flag: '🇩🇯' },
  { value: 'Dominica', longName: '', flag: '🇩🇲' },
  { value: 'Dominican Republic', longName: '', flag: '🇩🇴' },
  { value: 'Ecuador', longName: '', flag: '🇪🇨' },
  { value: 'Egypt', longName: '', flag: '🇪🇬' },
  { value: 'El Salvador', longName: '', flag: '🇸🇻' },
  { value: 'Equatorial Guinea', longName: '', flag: '🇬🇶' },
  { value: 'Eritrea', longName: '', flag: '🇪🇷' },
  { value: 'Estonia', longName: '', flag: '🇪🇪' },
  { value: 'Eswatini', longName: 'Kingdom of Eswatini', flag: '🇸🇿' },
  { value: 'Ethiopia', longName: '', flag: '🇪🇹' },
  { value: 'Fiji', longName: '', flag: '🇫🇯' },
  { value: 'Finland', longName: '', flag: '🇫🇮' },
  { value: 'France', longName: '', flag: '🇫🇷' },
  { value: 'Gabon', longName: '', flag: '🇬🇦' },
  { value: 'Gambia', longName: '', flag: '🇬🇲' },
  { value: 'Georgia', longName: '', flag: '🇬🇪' },
  { value: 'Germany', longName: '', flag: '🇩🇪' },
  { value: 'Ghana', longName: '', flag: '🇬🇭' },
  { value: 'Greece', longName: '', flag: '🇬🇷' },
  { value: 'Grenada', longName: '', flag: '🇬🇩' },
  { value: 'Guatemala', longName: '', flag: '🇬🇹' },
  { value: 'Guinea', longName: '', flag: '🇬🇳' },
  { value: 'Guinea-Bissau', longName: '', flag: '🇬🇼' },
  { value: 'Guyana', longName: '', flag: '🇬🇾' },
  { value: 'Haiti', longName: '', flag: '🇭🇹' },
  { value: 'Honduras', longName: '', flag: '🇭🇳' },
  { value: 'Hungary', longName: '', flag: '🇭🇺' },
  { value: 'Iceland', longName: '', flag: '🇮🇸' },
  { value: 'India', longName: '', flag: '🇮🇳' },
  { value: 'Indonesia', longName: '', flag: '🇮🇩' },
  { value: 'Iran', longName: 'Islamic Republic of Iran', flag: '🇮🇷' },
  { value: 'Iraq', longName: '', flag: '🇮🇶' },
  { value: 'Ireland', longName: '', flag: '🇮🇪' },
  { value: 'Israel', longName: '', flag: '🇮🇱' },
  { value: 'Italy', longName: '', flag: '🇮🇹' },
  { value: 'Jamaica', longName: '', flag: '🇯🇲' },
  { value: 'Japan', longName: '', flag: '🇯🇵' },
  { value: 'Jordan', longName: '', flag: '🇯🇴' },
  { value: 'Kazakhstan', longName: '', flag: '🇰🇿' },
  { value: 'Kenya', longName: '', flag: '🇰🇪' },
  { value: 'Kiribati', longName: '', flag: '🇰🇮' },
  { value: 'Kuwait', longName: '', flag: '🇰🇼' },
  { value: 'Kyrgyzstan', longName: '', flag: '🇰🇬' },
  { value: 'Laos', longName: '', flag: '🇱🇦' },
  { value: 'Latvia', longName: '', flag: '🇱🇻' },
  { value: 'Lebanon', longName: '', flag: '🇱🇧' },
  { value: 'Lesotho', longName: '', flag: '🇱🇸' },
  { value: 'Liberia', longName: '', flag: '🇱🇷' },
  { value: 'Libya', longName: '', flag: '🇱🇾' },
  { value: 'Liechtenstein', longName: '', flag: '🇱🇮' },
  { value: 'Lithuania', longName: '', flag: '🇱🇹' },
  { value: 'Luxembourg', longName: '', flag: '🇱🇺' },
  { value: 'Madagascar', longName: '', flag: '🇲🇬' },
  { value: 'Malawi', longName: '', flag: '🇲🇼' },
  { value: 'Malaysia', longName: '', flag: '🇲🇾' },
  { value: 'Maldives', longName: '', flag: '🇲🇻' },
  { value: 'Mali', longName: '', flag: '🇲🇱' },
  { value: 'Malta', longName: '', flag: '🇲🇹' },
  { value: 'Marshall Islands', longName: '', flag: '🇲🇭' },
  { value: 'Mauritania', longName: '', flag: '🇲🇷' },
  { value: 'Mauritius', longName: '', flag: '🇲🇺' },
  { value: 'Mexico', longName: '', flag: '🇲🇽' },
  { value: 'Micronesia', longName: '', flag: '🇫🇲' },
  { value: 'Moldova', longName: '', flag: '🇲🇩' },
  { value: 'Monaco', longName: '', flag: '🇲🇨' },
  { value: 'Mongolia', longName: '', flag: '🇲🇳' },
  { value: 'Montenegro', longName: '', flag: '🇲🇪' },
  { value: 'Morocco', longName: '', flag: '🇲🇦' },
  { value: 'Mozambique', longName: '', flag: '🇲🇿' },
  {
    value: 'Myanmar',
    longName: 'Republic of the Union of Myanmar',
    flag: '🇲🇲',
  },
  { value: 'Namibia', longName: '', flag: '🇳🇦' },
  { value: 'Nauru', longName: '', flag: '🇳🇷' },
  { value: 'Nepal', longName: '', flag: '🇳🇵' },
  {
    value: 'Netherlands',
    longName: 'Kingdom of the Netherlands',
    flag: '🇳🇱',
  },
  { value: 'New Zealand', longName: '', flag: '🇳🇿' },
  { value: 'Nicaragua', longName: '', flag: '🇳🇮' },
  { value: 'Niger', longName: '', flag: '🇳🇪' },
  { value: 'Nigeria', longName: '', flag: '🇳🇬' },
  {
    value: 'North Korea',
    longName: 'Democratic People’s Republic of Korea',
    flag: '🇰🇵',
  },
  {
    value: 'North Macedonia',
    longName: 'Republic of North Macedonia',
    flag: '🇲🇰',
  },
  { value: 'Norway', longName: '', flag: '🇳🇴' },
  { value: 'Oman', longName: '', flag: '🇴🇲' },
  { value: 'Pakistan', longName: '', flag: '🇵🇰' },
  { value: 'Palau', longName: '', flag: '🇵🇼' },
  { value: 'Panama', longName: '', flag: '🇵🇦' },
  { value: 'Papua New Guinea', longName: '', flag: '🇵🇬' },
  { value: 'Paraguay', longName: '', flag: '🇵🇾' },
  { value: 'Peru', longName: '', flag: '🇵🇪' },
  { value: 'Philippines', longName: '', flag: '🇵🇭' },
  { value: 'Poland', longName: '', flag: '🇵🇱' },
  { value: 'Portugal', longName: '', flag: '🇵🇹' },
  { value: 'Qatar', longName: '', flag: '🇶🇦' },
  { value: 'Romania', longName: '', flag: '🇷🇴' },
  { value: 'Russia', longName: 'Federation of Russia', flag: '🇷🇺' },
  { value: 'Rwanda', longName: '', flag: '🇷🇼' },
  { value: 'Saint Kitts and Nevis', longName: '', flag: '🇰🇳' },
  { value: 'Saint Lucia', longName: '', flag: '🇱🇨' },
  { value: 'Saint Vincent and the Grenadines', longName: '', flag: '🇻🇨' },
  { value: 'Samoa', longName: '', flag: '🇼🇸' },
  { value: 'San Marino', longName: '', flag: '🇸🇲' },
  { value: 'Sao Tome and Principe', longName: '', flag: '🇸🇹' },
  { value: 'Saudi Arabia', longName: '', flag: '🇸🇦' },
  { value: 'Senegal', longName: '', flag: '🇸🇳' },
  { value: 'Serbia', longName: '', flag: '🇷🇸' },
  { value: 'Seychelles', longName: '', flag: '🇸🇨' },
  { value: 'Sierra Leone', longName: '', flag: '🇸🇱' },
  { value: 'Singapore', longName: '', flag: '🇸🇬' },
  { value: 'Slovakia', longName: '', flag: '🇸🇰' },
  { value: 'Slovenia', longName: '', flag: '🇸🇮' },
  { value: 'Solomon Islands', longName: '', flag: '🇸🇧' },
  { value: 'Somalia', longName: '', flag: '🇸🇴' },
  { value: 'South Africa', longName: '', flag: '🇿🇦' },
  { value: 'South Korea', longName: '', flag: '🇰🇷' },
  { value: 'South Sudan', longName: '', flag: '🇸🇸' },
  { value: 'Spain', longName: '', flag: '🇪🇸' },
  { value: 'Sri Lanka', longName: '', flag: '🇱🇰' },
  { value: 'Sudan', longName: '', flag: '🇸🇩' },
  { value: 'Suriname', longName: '', flag: '🇸🇷' },
  { value: 'Sweden', longName: '', flag: '🇸🇪' },
  { value: 'Switzerland', longName: '', flag: '🇨🇭' },
  { value: 'Syria', longName: '', flag: '🇸🇾' },
  { value: 'Tajikistan', longName: '', flag: '🇹🇯' },
  { value: 'Tanzania', longName: 'United Republic of Tanzania', flag: '🇹🇿' },
  { value: 'Thailand', longName: '', flag: '🇹🇭' },
  { value: 'Timor-Leste', longName: '', flag: '🇹🇱' },
  { value: 'Togo', longName: '', flag: '🇹🇬' },
  { value: 'Tonga', longName: '', flag: '🇹🇴' },
  { value: 'Trinidad and Tobago', longName: '', flag: '🇹🇹' },
  { value: 'Tunisia', longName: '', flag: '🇹🇳' },
  { value: 'Turkey', longName: 'Republic of Turkey', flag: '🇹🇷' },
  { value: 'Turkmenistan', longName: '', flag: '🇹🇲' },
  { value: 'Tuvalu', longName: '', flag: '🇹🇻' },
  { value: 'Uganda', longName: '', flag: '🇺🇬' },
  { value: 'Ukraine', longName: '', flag: '🇺🇦' },
  { value: 'United Arab Emirates', longName: '', flag: '🇦🇪' },
  {
    value: 'United Kingdom',
    longName: 'United Kingdom of Great Britain and Northern Ireland',
    flag: '🇬🇧',
  },
  {
    value: 'United States',
    longName: 'United States of America',
    flag: '🇺🇸',
  },
  { value: 'Uruguay', longName: '', flag: '🇺🇾' },
  { value: 'Uzbekistan', longName: '', flag: '🇺🇿' },
  { value: 'Vanuatu', longName: '', flag: '🇻🇺' },
  { value: 'Vatican City', longName: '', flag: '🇻🇦' },
  {
    value: 'Venezuela',
    longName: 'Bolivarian Republic of Venezuela',
    flag: '🇻🇪',
  },
  {
    value: 'Vietnam',
    longName: 'Socialist Republic of Viet Nam',
    flag: '🇻🇳',
  },
  { value: 'Yemen', longName: '', flag: '🇾🇪' },
  { value: 'Zambia', longName: '', flag: '🇿🇲' },
  { value: 'Zimbabwe', longName: '', flag: '🇿🇼' },
];
