export interface Country {
  label: string;
  value: string; // ISO‑3166‑1 alpha‑2 code
  longName: string; // Official long name or empty
  flag: string; // 🇦🇫 style emoji
}

export const countriesData: Country[] = [
  {
    label: 'Afghanistan',
    value: 'AF',
    longName: 'Islamic Republic of Afghanistan',
    flag: '🇦🇫',
  },
  { label: 'Albania', value: 'AL', longName: '', flag: '🇦🇱' },
  { label: 'Algeria', value: 'DZ', longName: '', flag: '🇩🇿' },
  { label: 'Andorra', value: 'AD', longName: '', flag: '🇦🇩' },
  { label: 'Angola', value: 'AO', longName: '', flag: '🇦🇴' },
  { label: 'Antigua and Barbuda', value: 'AG', longName: '', flag: '🇦🇬' },
  { label: 'Argentina', value: 'AR', longName: '', flag: '🇦🇷' },
  { label: 'Armenia', value: 'AM', longName: '', flag: '🇦🇲' },
  { label: 'Australia', value: 'AU', longName: '', flag: '🇦🇺' },
  { label: 'Austria', value: 'AT', longName: '', flag: '🇦🇹' },
  { label: 'Azerbaijan', value: 'AZ', longName: '', flag: '🇦🇿' },
  { label: 'Bahamas', value: 'BS', longName: '', flag: '🇧🇸' },
  { label: 'Bahrain', value: 'BH', longName: '', flag: '🇧🇭' },
  { label: 'Bangladesh', value: 'BD', longName: '', flag: '🇧🇩' },
  { label: 'Barbados', value: 'BB', longName: '', flag: '🇧🇧' },
  { label: 'Belarus', value: 'BY', longName: '', flag: '🇧🇾' },
  { label: 'Belgium', value: 'BE', longName: '', flag: '🇧🇪' },
  { label: 'Belize', value: 'BZ', longName: '', flag: '🇧🇿' },
  { label: 'Benin', value: 'BJ', longName: '', flag: '🇧🇯' },
  { label: 'Bhutan', value: 'BT', longName: '', flag: '🇧🇹' },
  {
    label: 'Bolivia',
    value: 'BO',
    longName: 'Plurinational State of Bolivia',
    flag: '🇧🇴',
  },
  { label: 'Bosnia and Herzegovina', value: 'BA', longName: '', flag: '🇧🇦' },
  { label: 'Botswana', value: 'BW', longName: '', flag: '🇧🇼' },
  { label: 'Brazil', value: 'BR', longName: '', flag: '🇧🇷' },
  { label: 'Brunei', value: 'BN', longName: 'Negara Brunei Darussalam', flag: '🇧🇳' },
  { label: 'Bulgaria', value: 'BG', longName: '', flag: '🇧🇬' },
  { label: 'Burkina Faso', value: 'BF', longName: '', flag: '🇧🇫' },
  { label: 'Burundi', value: 'BI', longName: '', flag: '🇧🇮' },
  { label: 'Cabo Verde', value: 'CV', longName: '', flag: '🇨🇻' },
  { label: 'Cambodia', value: 'KH', longName: '', flag: '🇰🇭' },
  { label: 'Cameroon', value: 'CM', longName: '', flag: '🇨🇲' },
  { label: 'Canada', value: 'CA', longName: '', flag: '🇨🇦' },
  { label: 'Central African Republic', value: 'CF', longName: '', flag: '🇨🇫' },
  { label: 'Chad', value: 'TD', longName: '', flag: '🇹🇩' },
  { label: 'Chile', value: 'CL', longName: '', flag: '🇨🇱' },
  { label: 'China', value: 'CN', longName: 'People’s Republic of China', flag: '🇨🇳' },
  { label: 'Colombia', value: 'CO', longName: '', flag: '🇨🇴' },
  { label: 'Comoros', value: 'KM', longName: '', flag: '🇰🇲' },
  { label: 'Congo', value: 'CG', longName: 'Congo‑Brazzaville', flag: '🇨🇬' },
  { label: 'Costa Rica', value: 'CR', longName: '', flag: '🇨🇷' },
  { label: 'Croatia', value: 'HR', longName: '', flag: '🇭🇷' },
  { label: 'Cuba', value: 'CU', longName: '', flag: '🇨🇺' },
  { label: 'Cyprus', value: 'CY', longName: '', flag: '🇨🇾' },
  { label: 'Czechia', value: 'CZ', longName: 'Czech Republic', flag: '🇨🇿' },
  { label: 'Democratic Republic of the Congo', value: 'CD', longName: '', flag: '🇨🇩' },
  { label: 'Denmark', value: 'DK', longName: '', flag: '🇩🇰' },
  { label: 'Djibouti', value: 'DJ', longName: '', flag: '🇩🇯' },
  { label: 'Dominica', value: 'DM', longName: '', flag: '🇩🇲' },
  { label: 'Dominican Republic', value: 'DO', longName: '', flag: '🇩🇴' },
  { label: 'Ecuador', value: 'EC', longName: '', flag: '🇪🇨' },
  { label: 'Egypt', value: 'EG', longName: '', flag: '🇪🇬' },
  { label: 'El Salvador', value: 'SV', longName: '', flag: '🇸🇻' },
  { label: 'Equatorial Guinea', value: 'GQ', longName: '', flag: '🇬🇶' },
  { label: 'Eritrea', value: 'ER', longName: '', flag: '🇪🇷' },
  { label: 'Estonia', value: 'EE', longName: '', flag: '🇪🇪' },
  { label: 'Eswatini', value: 'SZ', longName: 'Kingdom of Eswatini', flag: '🇸🇿' },
  { label: 'Ethiopia', value: 'ET', longName: '', flag: '🇪🇹' },
  { label: 'Fiji', value: 'FJ', longName: '', flag: '🇫🇯' },
  { label: 'Finland', value: 'FI', longName: '', flag: '🇫🇮' },
  { label: 'France', value: 'FR', longName: '', flag: '🇫🇷' },
  { label: 'Gabon', value: 'GA', longName: '', flag: '🇬🇦' },
  { label: 'Gambia', value: 'GM', longName: '', flag: '🇬🇲' },
  { label: 'Georgia', value: 'GE', longName: '', flag: '🇬🇪' },
  { label: 'Germany', value: 'DE', longName: '', flag: '🇩🇪' },
  { label: 'Ghana', value: 'GH', longName: '', flag: '🇬🇭' },
  { label: 'Greece', value: 'GR', longName: '', flag: '🇬🇷' },
  { label: 'Grenada', value: 'GD', longName: '', flag: '🇬🇩' },
  { label: 'Guatemala', value: 'GT', longName: '', flag: '🇬🇹' },
  { label: 'Guinea', value: 'GN', longName: '', flag: '🇬🇳' },
  { label: 'Guinea-Bissau', value: 'GW', longName: '', flag: '🇬🇼' },
  { label: 'Guyana', value: 'GY', longName: '', flag: '🇬🇾' },
  { label: 'Haiti', value: 'HT', longName: '', flag: '🇭🇹' },
  { label: 'Honduras', value: 'HN', longName: '', flag: '🇭🇳' },
  { label: 'Hungary', value: 'HU', longName: '', flag: '🇭🇺' },
  { label: 'Iceland', value: 'IS', longName: '', flag: '🇮🇸' },
  { label: 'India', value: 'IN', longName: '', flag: '🇮🇳' },
  { label: 'Indonesia', value: 'ID', longName: '', flag: '🇮🇩' },
  { label: 'Iran', value: 'IR', longName: 'Islamic Republic of Iran', flag: '🇮🇷' },
  { label: 'Iraq', value: 'IQ', longName: '', flag: '🇮🇶' },
  { label: 'Ireland', value: 'IE', longName: '', flag: '🇮🇪' },
  { label: 'Israel', value: 'IL', longName: '', flag: '🇮🇱' },
  { label: 'Italy', value: 'IT', longName: '', flag: '🇮🇹' },
  { label: 'Jamaica', value: 'JM', longName: '', flag: '🇯🇲' },
  { label: 'Japan', value: 'JP', longName: '', flag: '🇯🇵' },
  { label: 'Jordan', value: 'JO', longName: '', flag: '🇯🇴' },
  { label: 'Kazakhstan', value: 'KZ', longName: '', flag: '🇰🇿' },
  { label: 'Kenya', value: 'KE', longName: '', flag: '🇰🇪' },
  { label: 'Kiribati', value: 'KI', longName: '', flag: '🇰🇮' },
  { label: 'Kuwait', value: 'KW', longName: '', flag: '🇰🇼' },
  { label: 'Kyrgyzstan', value: 'KG', longName: '', flag: '🇰🇬' },
  { label: 'Laos', value: 'LA', longName: '', flag: '🇱🇦' },
  { label: 'Latvia', value: 'LV', longName: '', flag: '🇱🇻' },
  { label: 'Lebanon', value: 'LB', longName: '', flag: '🇱🇧' },
  { label: 'Lesotho', value: 'LS', longName: '', flag: '🇱🇸' },
  { label: 'Liberia', value: 'LR', longName: '', flag: '🇱🇷' },
  { label: 'Libya', value: 'LY', longName: '', flag: '🇱🇾' },
  { label: 'Liechtenstein', value: 'LI', longName: '', flag: '🇱🇮' },
  { label: 'Lithuania', value: 'LT', longName: '', flag: '🇱🇹' },
  { label: 'Luxembourg', value: 'LU', longName: '', flag: '🇱🇺' },
  { label: 'Madagascar', value: 'MG', longName: '', flag: '🇲🇬' },
  { label: 'Malawi', value: 'MW', longName: '', flag: '🇲🇼' },
  { label: 'Malaysia', value: 'MY', longName: '', flag: '🇲🇾' },
  { label: 'Maldives', value: 'MV', longName: '', flag: '🇲🇻' },
  { label: 'Mali', value: 'ML', longName: '', flag: '🇲🇱' },
  { label: 'Malta', value: 'MT', longName: '', flag: '🇲🇹' },
  { label: 'Marshall Islands', value: 'MH', longName: '', flag: '🇲🇭' },
  { label: 'Mauritania', value: 'MR', longName: '', flag: '🇲🇷' },
  { label: 'Mauritius', value: 'MU', longName: '', flag: '🇲🇺' },
  { label: 'Mexico', value: 'MX', longName: '', flag: '🇲🇽' },
  { label: 'Micronesia', value: 'FM', longName: '', flag: '🇫🇲' },
  { label: 'Moldova', value: 'MD', longName: '', flag: '🇲🇩' },
  { label: 'Monaco', value: 'MC', longName: '', flag: '🇲🇨' },
  { label: 'Mongolia', value: 'MN', longName: '', flag: '🇲🇳' },
  { label: 'Montenegro', value: 'ME', longName: '', flag: '🇲🇪' },
  { label: 'Morocco', value: 'MA', longName: '', flag: '🇲🇦' },
  { label: 'Mozambique', value: 'MZ', longName: '', flag: '🇲🇿' },
  {
    label: 'Myanmar',
    value: 'MM',
    longName: 'Republic of the Union of Myanmar',
    flag: '🇲🇲',
  },
  { label: 'Namibia', value: 'NA', longName: '', flag: '🇳🇦' },
  { label: 'Nauru', value: 'NR', longName: '', flag: '🇳🇷' },
  { label: 'Nepal', value: 'NP', longName: '', flag: '🇳🇵' },
  {
    label: 'Netherlands',
    value: 'NL',
    longName: 'Kingdom of the Netherlands',
    flag: '🇳🇱',
  },
  { label: 'New Zealand', value: 'NZ', longName: '', flag: '🇳🇿' },
  { label: 'Nicaragua', value: 'NI', longName: '', flag: '🇳🇮' },
  { label: 'Niger', value: 'NE', longName: '', flag: '🇳🇪' },
  { label: 'Nigeria', value: 'NG', longName: '', flag: '🇳🇬' },
  {
    label: 'North Korea',
    value: 'KP',
    longName: 'Democratic People’s Republic of Korea',
    flag: '🇰🇵',
  },
  {
    label: 'North Macedonia',
    value: 'MK',
    longName: 'Republic of North Macedonia',
    flag: '🇲🇰',
  },
  { label: 'Norway', value: 'NO', longName: '', flag: '🇳🇴' },
  { label: 'Oman', value: 'OM', longName: '', flag: '🇴🇲' },
  { label: 'Pakistan', value: 'PK', longName: '', flag: '🇵🇰' },
  { label: 'Palau', value: 'PW', longName: '', flag: '🇵🇼' },
  { label: 'Panama', value: 'PA', longName: '', flag: '🇵🇦' },
  { label: 'Papua New Guinea', value: 'PG', longName: '', flag: '🇵🇬' },
  { label: 'Paraguay', value: 'PY', longName: '', flag: '🇵🇾' },
  { label: 'Peru', value: 'PE', longName: '', flag: '🇵🇪' },
  { label: 'Philippines', value: 'PH', longName: '', flag: '🇵🇭' },
  { label: 'Poland', value: 'PL', longName: '', flag: '🇵🇱' },
  { label: 'Portugal', value: 'PT', longName: '', flag: '🇵🇹' },
  { label: 'Qatar', value: 'QA', longName: '', flag: '🇶🇦' },
  { label: 'Romania', value: 'RO', longName: '', flag: '🇷🇴' },
  { label: 'Russia', value: 'RU', longName: 'Federation of Russia', flag: '🇷🇺' },
  { label: 'Rwanda', value: 'RW', longName: '', flag: '🇷🇼' },
  { label: 'Saint Kitts and Nevis', value: 'KN', longName: '', flag: '🇰🇳' },
  { label: 'Saint Lucia', value: 'LC', longName: '', flag: '🇱🇨' },
  { label: 'Saint Vincent and the Grenadines', value: 'VC', longName: '', flag: '🇻🇨' },
  { label: 'Samoa', value: 'WS', longName: '', flag: '🇼🇸' },
  { label: 'San Marino', value: 'SM', longName: '', flag: '🇸🇲' },
  { label: 'Sao Tome and Principe', value: 'ST', longName: '', flag: '🇸🇹' },
  { label: 'Saudi Arabia', value: 'SA', longName: '', flag: '🇸🇦' },
  { label: 'Senegal', value: 'SN', longName: '', flag: '🇸🇳' },
  { label: 'Serbia', value: 'RS', longName: '', flag: '🇷🇸' },
  { label: 'Seychelles', value: 'SC', longName: '', flag: '🇸🇨' },
  { label: 'Sierra Leone', value: 'SL', longName: '', flag: '🇸🇱' },
  { label: 'Singapore', value: 'SG', longName: '', flag: '🇸🇬' },
  { label: 'Slovakia', value: 'SK', longName: '', flag: '🇸🇰' },
  { label: 'Slovenia', value: 'SI', longName: '', flag: '🇸🇮' },
  { label: 'Solomon Islands', value: 'SB', longName: '', flag: '🇸🇧' },
  { label: 'Somalia', value: 'SO', longName: '', flag: '🇸🇴' },
  { label: 'South Africa', value: 'ZA', longName: '', flag: '🇿🇦' },
  { label: 'South Korea', value: 'KR', longName: '', flag: '🇰🇷' },
  { label: 'South Sudan', value: 'SS', longName: '', flag: '🇸🇸' },
  { label: 'Spain', value: 'ES', longName: '', flag: '🇪🇸' },
  { label: 'Sri Lanka', value: 'LK', longName: '', flag: '🇱🇰' },
  { label: 'Sudan', value: 'SD', longName: '', flag: '🇸🇩' },
  { label: 'Suriname', value: 'SR', longName: '', flag: '🇸🇷' },
  { label: 'Sweden', value: 'SE', longName: '', flag: '🇸🇪' },
  { label: 'Switzerland', value: 'CH', longName: '', flag: '🇨🇭' },
  { label: 'Syria', value: 'SY', longName: '', flag: '🇸🇾' },
  { label: 'Tajikistan', value: 'TJ', longName: '', flag: '🇹🇯' },
  { label: 'Tanzania', value: 'TZ', longName: 'United Republic of Tanzania', flag: '🇹🇿' },
  { label: 'Thailand', value: 'TH', longName: '', flag: '🇹🇭' },
  { label: 'Timor-Leste', value: 'TL', longName: '', flag: '🇹🇱' },
  { label: 'Togo', value: 'TG', longName: '', flag: '🇹🇬' },
  { label: 'Tonga', value: 'TO', longName: '', flag: '🇹🇴' },
  { label: 'Trinidad and Tobago', value: 'TT', longName: '', flag: '🇹🇹' },
  { label: 'Tunisia', value: 'TN', longName: '', flag: '🇹🇳' },
  { label: 'Turkey', value: 'TR', longName: 'Republic of Turkey', flag: '🇹🇷' },
  { label: 'Turkmenistan', value: 'TM', longName: '', flag: '🇹🇲' },
  { label: 'Tuvalu', value: 'TV', longName: '', flag: '🇹🇻' },
  { label: 'Uganda', value: 'UG', longName: '', flag: '🇺🇬' },
  { label: 'Ukraine', value: 'UA', longName: '', flag: '🇺🇦' },
  { label: 'United Arab Emirates', value: 'AE', longName: '', flag: '🇦🇪' },
  {
    label: 'United Kingdom',
    value: 'GB',
    longName: 'United Kingdom of Great Britain and Northern Ireland',
    flag: '🇬🇧',
  },
  {
    label: 'United States',
    value: 'US',
    longName: 'United States of America',
    flag: '🇺🇸',
  },
  { label: 'Uruguay', value: 'UY', longName: '', flag: '🇺🇾' },
  { label: 'Uzbekistan', value: 'UZ', longName: '', flag: '🇺🇿' },
  { label: 'Vanuatu', value: 'VU', longName: '', flag: '🇻🇺' },
  { label: 'Vatican City', value: 'VA', longName: '', flag: '🇻🇦' },
  {
    label: 'Venezuela',
    value: 'VE',
    longName: 'Bolivarian Republic of Venezuela',
    flag: '🇻🇪',
  },
  {
    label: 'Vietnam',
    value: 'VN',
    longName: 'Socialist Republic of Viet Nam',
    flag: '🇻🇳',
  },
  { label: 'Yemen', value: 'YE', longName: '', flag: '🇾🇪' },
  { label: 'Zambia', value: 'ZM', longName: '', flag: '🇿🇲' },
  { label: 'Zimbabwe', value: 'ZW', longName: '', flag: '🇿🇼' },
];
